Algoritmo "semnome"
// Autor(a)    : Tiago Oliveira
Var
  numero1, numero2: inteiro
Inicio
escreval("Digite o primeiro número")
leia(numero1)
escreval("Digite o segundo número")
leia(numero2)
escreval("Resultado da soma:", (numero1+numero2))
escreval("Resultado da subtração:", (numero1-numero2))
escreval("Resultado da multiplicação:", (numero1*numero2))
escreval("Resultado da divisão:", (numero1/numero2))
Fimalgoritmo