Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Autor(a)    : Tiago Oliveira
Var
  nota1, nota2, nota3: Real
  nomeAluno: caracter
Inicio
escreval("Informe o nome do aluno: ")
leia(nomeAluno)
escreval("Digite a primeira nota:")
leia(nota1)
escreval("Digite a segunda nota:")
leia(nota2)
escreval("Digite a terceira nota:")
leia(nota3)
escreval("Nome do aluno:", nomeAluno)
escreval("Média aritmética das notas:", ((nota1+nota2+nota3)/3) )

Fimalgoritmo